title: Recollate jekyll+webpack test
email: github@recollate.com
description: ""
url: ""
baseurl: '/emersonleite'
twitter_username: recollateagency
github_username:  recollate
permalink: "/:title:output_ext"

collections:
  projects:
    output: true

markdown: kramdown

destination: docs
source: src
exclude: ['node_modules']

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: emersonleitedev
