title: Emerson Leite - emersonleite.dev
curriculo: true
description: "Desenvolvedor Javascript | Front-end | UX/ UI Desing"
url: "https://www.emersonleite.dev"
baseurl: 
permalink: "/:title:output_ext"

markdown: kramdown

destination: docs
source: src
exclude: ['node_modules']

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: emersonleitedev
